# Generated by Django 3.2 on 2021-04-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Place name')),
                ('code', models.TextField(verbose_name='QR-code')),
            ],
            options={
                'verbose_name': 'Place',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Review text')),
                ('author', models.TextField(verbose_name='Reviewer name')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.place', verbose_name='Place')),
            ],
        ),
    ]
