# Generated by Django 3.2 on 2021-04-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210425_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_id',
            field=models.IntegerField(default=0, verbose_name='Reviewer id'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.BinaryField(default=None, verbose_name='Photo'),
        ),
    ]
