# Generated by Django 3.2 on 2021-04-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_review_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(unique=True, verbose_name='Telegram username (like @user)')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='author_id',
            field=models.TextField(default=0, verbose_name='Reviewer id'),
        ),
    ]
